name: Submit 4-Queens Token
description: Paste the token from the 4-Queens game to unlock Airof’s journey.
title: "Token submission"
labels: ["challenge"]
body:
  - type: input
    id: token
    attributes:
      label: Token
      description: "Paste exactly the token shown by the game."
      placeholder: "the key"
    validations:
      required: true
