name: Update AniList Stats

on:
  schedule:
    - cron: "0 3 * * *"   # daily at 03:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: update-anilist
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Sync with remote (pre-edit)
        run: |
          git fetch origin main
          git rebase origin/main || (git rebase --abort && git reset --hard origin/main)

      - name: Update README with AniList stats
        run: node scripts/update-anilist.mjs
        env:
          ANILIST_USERNAME: Airof

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: update AniList stats"
            git pull --rebase origin main || true
            git push origin main
          else
            echo "No changes to commit."
          fi
