name: Update Weather & AniList (Shiraz)

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch: {}       # allow manual run

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Update README with Shiraz weather
        run: node scripts/update-weather.mjs

      - name: Update README with AniList stats
        run: node scripts/update-anilist.mjs
        env:
          ANILIST_USERNAME: Airof

      - name: Pull latest changes and resolve conflicts
        run: |
          git config pull.rebase true
          git fetch origin
          git pull origin main --rebase || {
            echo "Merge conflict detected. Attempting to resolve by keeping remote changes."
            git rebase --abort || true
            git fetch origin
            git reset --hard origin/main
            # Re-run the update scripts to ensure latest data
            node scripts/update-weather.mjs
            node scripts/update-anilist.mjs
          }

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add README.md
            git commit -m "chore: update weather (Shiraz) & AniList stats"
            git push
          else
            echo "No changes to commit."
          fi