name: Validate solution and reply
on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  validate:
    if: contains(github.event.issue.labels.*.name, 'challenge')
    runs-on: ubuntu-latest
    steps:
      - name: Check token and reply
        uses: actions/github-script@v7
        env:
          JOURNEY_MD: ${{ secrets.JOURNEY_MD }}
        with:
          script: |
            const body = (context.payload.issue.body || "").trim();

            // Exact match for the token with special chars. Use a plain string compare.
            const TOKEN = "*@'queens_solved'@*";
            const ok = body.includes(TOKEN);

            if (!ok) {
              await github.rest.issues.createComment({
                owner: context.repo.owner, repo: context.repo.repo,
                issue_number: context.issue.number,
                body: "❌ Not quite. Make sure you solved the board and pasted the token exactly as shown."
              });
              return;
            }

            const journey = process.env.JOURNEY_MD || "_(Missing JOURNEY_MD secret)_";
            await github.rest.issues.createComment({
              owner: context.repo.owner, repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `✅ **Correct!** You unlocked Airof’s journal:\n\n${journey}`
            });

            // Optional: keep it tidy—close and lock the issue so it feels personal
            await github.rest.issues.update({
              owner: context.repo.owner, repo: context.repo.repo,
              issue_number: context.issue.number, state: "closed"
            });
            await github.rest.issues.lock({
              owner: context.repo.owner, repo: context.repo.repo,
              issue_number: context.issue.number, lock_reason: "resolved"
            });
